# Generated by Django 4.0.4 on 2022-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_person_task_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(null=True, verbose_name="Дата"),
        ),
    ]
