# Generated by Django 4.0.4 on 2022-06-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_task_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("surname", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
            ],
        ),
        migrations.RemoveField(model_name="task", name="person",),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.DeleteModel(name="Person",),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.user"
            ),
        ),
    ]
