# Generated by Django 4.0.5 on 2022-06-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_date_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
