# Generated by Django 4.0.5 on 2022-06-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_task_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="surname",),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="main.user"
            ),
        ),
    ]
