# Generated by Django 4.0.5 on 2022-06-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_user_surname_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задачу', 'verbose_name_plural': 'Задачи'},
        ),
    ]
