# Generated by Django 4.0.5 on 2022-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_executed",
            field=models.BooleanField(default=False),
        ),
    ]
