# Generated by Django 4.0.5 on 2022-06-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_task_is_executed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="date", field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="get_tasks",
                to="main.user",
            ),
        ),
    ]
