# Generated by Django 4.0.5 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_task_date_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Название даты"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(null=True, verbose_name="Дата"),
        ),
    ]
