# Generated by Django 4.0.5 on 2022-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_task_date_name_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
